Default: &defaults
  user: yesod
  password: yesod
  host: localhost
  port: 5432
  database: yesod
  poolsize: 100

Development:
  <<: *defaults

Testing:
  # database: star-exec-presenter_test
  <<: *defaults

Staging:
  # database: star-exec-presenter_staging
  poolsize: 100
  <<: *defaults

Production:
  # database: star-exec-presenter_production
  poolsize: 100
  <<: *defaults
