Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  #approot: "http://localhost:3000"
  copyright: Stefan von der Krone | HTWK | IMN
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  approot: "http://nfa.imn.htwk-leipzig.de/termcomptest"
  <<: *defaults

Production:
  approot: "http://nfa.imn.htwk-leipzig.de/termcomp"
  <<: *defaults
